# 多媒體技術與應用 Homework 2

Author: 109590031 資工二 黃漢軒

## Part 1. 前置作業

### Step 1. 安裝相關套件

In [301]:
! pip3 install numpy --quiet
! pip3 install sklearn --quiet

### Step 2. 匯入相關套件

In [302]:
import numpy as np
from sklearn.model_selection import train_test_split

### Step 3. 讀取檔案並切割資料

In [303]:
# 預測資料
data = np.array([])
# 預測標籤
label = None

# 開啟資料特徵值檔案
with open("iris_x.txt") as f:
    list = []
    for i in range(150):
        list.append(np.array(f.readline().split(), dtype=float))
    data = np.array(list)

# 開啟資料標籤檔案
with open("iris_y.txt") as f:
    label = np.array(f.read().split(), dtype=int)

# 切割資料，指定 random_state = 20220413
x_train, x_test, y_train, y_test = train_test_split(data, label, random_state=20220413)

## Part 2. 訓練 Multiple regression

### Step 1. 匯入相關套件

In [304]:
import numpy as np
from sklearn import *
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

### Step 2. 使用 Linear Regression 進行擬合，並輸出 MSE 結果

In [305]:
# 使用線性迴歸類別
clt = LinearRegression()

# 擬合
clt.fit(x_train, y_train)

# 取得 MSE 值
mse = mean_squared_error(y_test, clt.predict(x_test))

# 印出結果
print("MSE =", mse)

MSE = 0.03805233566090977


## Part 3. 製作 Quadratic Discriminant Analysis 進行分析與評估

### Step 1. 匯入相關套件

In [306]:
import numpy as np
import numpy.linalg as nplg
import math

### Step 2. 撰寫 Quadratic Discriminant Analysis 類別

In [307]:
# 撰寫 QuadraticDiscriminantAnalysis
class _QuadraticDiscriminantAnalysis():
    # 建構子
    def __init__(self):
        self.mu = np.array([])
        self.cov = np.array([])
    # 擬合函式
    def fit(self, data, label):
        mu = []
        cov = []
        for i in range(np.max(label) + 1):
            pos = np.where(label == i)[0]
            tmp_data = data[pos,:]
            tmp_cov = np.cov(np.transpose(tmp_data))
            tmp_mu = np.mean(tmp_data,axis=0)
            mu.append(tmp_mu)
            cov.append(tmp_cov)
        self.mu = np.array(mu)
        self.cov = np.array(cov)
    # 預測函式
    def predict(self, tests):
        result = []
        for test in tests:
            list = []
            for i in range(len(self.mu)):
                # 使用 Quadratic discriminant classifier 的式子
                value = - 0.5 * math.log(nplg.norm(self.cov[i])) - 0.5 * np.dot(np.dot(np.transpose(test - self.mu[i]), nplg.inv(self.cov[i])), (test - self.mu[i]))
                list.append(value)
            values = np.array(list)
            result.append(np.argmax(values))
        return result

### Step 3. 使用撰寫的類別，並進行資料擬合

In [308]:
# 使用自己寫的 Quadratic Discriminant Analysis 類別
qda = _QuadraticDiscriminantAnalysis()

# 擬合
qda.fit(x_train, y_train)

### Step 4. 撰寫準確度測量與 ConfusionMatrix 函式

In [309]:
# 準確率函數，回傳 float 準確率
def getAccurate(y_true, y_pred) -> float:
    correct = 0
    for i in range(len(y_pred)):
        if(y_pred[i] == y_true[i]):
            correct += 1
    return correct / len(y_true)

# Confusion matrix，回傳 np.array
def getConfusionMatrix(y_true, y_pred) -> np.array:
    n = len(np.unique(y_true))
    result = np.empty((n, n), dtype=np.uint)
    result.fill(0)
    for i in range(len(y_pred)):
        result[y_true[i]][y_pred[i]] += 1
    return result

### Step 5. 預測並呈現結果

In [310]:
# 預測
predicted = qda.predict(x_test)

# 輸出結果
print("Accurate = %.4f%%" % (getAccurate(y_test, predicted) * 100))
print(f"Confusion Matrix: \n{getConfusionMatrix(y_test, predicted)}")

Accurate = 100.0000%
Confusion Matrix: 
[[10  0  0]
 [ 0 13  0]
 [ 0  0 15]]


## Part 4. 使用 scikit-learn 的 Quadratic Discriminant Analysis 進行分析與評估

### Step 1. 匯入相關套件

In [311]:
import numpy as np
from sklearn import *
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.metrics import confusion_matrix

### Step 2. 使用 sklearn 的類別並進行擬合、預測與輸出結果

In [312]:
# 使用 sklearn 的 QuadraticDiscriminantAnalysis 類別
qda = QuadraticDiscriminantAnalysis()

# 擬合
qda.fit(x_train, y_train)

# 預判
predicted = qda.predict(x_test)

# 得到準確率
accuracy = qda.score(x_test, y_test)

# 輸出結果
print("Accurate = %.4f%%" % (float(accuracy) * 100))
print(f"Confusion Matrix: \n{confusion_matrix(y_test, predicted)}")

Accurate = 100.0000%
Confusion Matrix: 
[[10  0  0]
 [ 0 13  0]
 [ 0  0 15]]
